### ISSUE TITLE
Get on dockerhub

### ISSUE THREAD

**Issue by ConnorFoody** [rpi-nsl/NSL-Spindle#7]
The build docker script in /vehicle/vehicle-node/docker/buildDocker.sh tries to push to the nslrpi dockerhub account. I should get on it if we want to make distribution easier.

**Comment by akaanirban** [comment]
I forgot about that, will add you. We tried adding a organization level thing much like the rpi-nsl on Github,

**Comment by ConnorFoody** [comment]
Got the invite, thanks!
